### ISSUE TITLE
Papier Prototype

### ISSUE THREAD

**Issue by rsgc-dunphy-j** [rsgc-edwards-g/RateMySchmeacher#1]
We need to get the basic interface down

**Comment by rsgc-power-r** [comment]
but actually everyone is working on it

**Comment by rsgc-edwards-g** [comment]
So the first paper prototype session is done and I didn't get any feedback on design from Mr. Ruscitti. The video of the session is here. 
https://youtu.be/jSG0_ePWYNU 
I'm also going to post pictures of each of the pages we have.

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-17 at 5 05 pm](https://cloud.githubusercontent.com/assets/14296586/11883402/b99d7a8a-a4e0-11e5-9fbf-e0f4080ed0ca.jpg)

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-17 at 5 05 pm 2](https://cloud.githubusercontent.com/assets/14296586/11883404/c2361030-a4e0-11e5-9881-6b193b61fb2f.jpg)

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-17 at 5 05 pm 3](https://cloud.githubusercontent.com/assets/14296586/11883406/c64fed9e-a4e0-11e5-9d2d-22e9fe3878b4.jpg)

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-17 at 5 06 pm](https://cloud.githubusercontent.com/assets/14296586/11883408/c9e565e2-a4e0-11e5-9772-46e4f2032c4d.jpg)

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-17 at 5 06 pm 3](https://cloud.githubusercontent.com/assets/14296586/11883410/cde56386-a4e0-11e5-8dcc-05de04a07d1e.jpg)

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-17 at 5 06 pm 2](https://cloud.githubusercontent.com/assets/14296586/11883417/d2e39e0c-a4e0-11e5-9caa-77ed9bd88106.jpg)

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-17 at 5 07 pm](https://cloud.githubusercontent.com/assets/14296586/11883422/d7c2c39e-a4e0-11e5-9f9c-92f02f89ba69.jpg)

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-17 at 5 07 pm 2](https://cloud.githubusercontent.com/assets/14296586/11883425/da4247c0-a4e0-11e5-893a-fdb7b9615044.jpg)

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-17 at 5 14 pm](https://cloud.githubusercontent.com/assets/14296586/11883526/9a4fab2a-a4e1-11e5-89fe-4ed67d21f4ac.jpg)

I am only posting this because I had all the paper prototypes and forgot them at home so I had to redraw them. This particular page was done by John Dunphy.

**Comment by rsgc-edwards-g** [comment]
![photo on 2015-12-17 at 5 15 pm](https://cloud.githubusercontent.com/assets/14296586/11883552/c8016f18-a4e1-11e5-9818-fef3f00530a8.jpg)

Same reason for this page. I also misspelled Shmee in my home page. This is Ryan's home page design.

**Comment by rgordonathome** [comment]
Here is the feedback I heard from Mr. Ruscitti for changes:
- Change wording on first page.
- Use same authentication as FirstClass email if possible.
- Doesn't want to have to approve students (whether they are part of class or not). This should be noted as a requirement.
- Get rid of overall rating for a course – wants to know details on class by class basis.
- Ensure that rating for a student as viewed by a teacher is anonymous.
- Once logged in, wants to stay logged in.

So you want to keep track of not just suggestions for changing the interface but all his suggestions for changing / modifying your system.  Sounds like there was a lot he liked, but I haven't seen where you've tracked what he commented on in this video – I've listed what I heard above.

@rsgc-power-r you mentioned everyone worked on the paper prototype process, but I see that @rsgc-edwards-g posted all the photos of the paper prototypes, posted the video, and conducted the paper prototype feedback session with Mr. Ruscitti. What did @rsgc-dunphy-j do?
