### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by rsgc-dunphy-j** [rsgc-edwards-g/RateMySchmeacher#11]

**Comment by rsgc-edwards-g** [comment]
Dunphy, you can close this by linking to my latest commit.

**Comment by rgordonathome** [comment]
This issue was created without a label or milestone.

**Comment by rgordonathome** [comment]
This issue was closed without a link to a commit.

**Comment by rsgc-dunphy-j** [comment]
98b97501a705886f2323d5c5f148b1c5c4f370e3
