### ISSUE TITLE
Teacher Register Page

### ISSUE THREAD

**Issue by rsgc-dunphy-j** [rsgc-edwards-g/RateMySchmeacher#18]
After registering a teacher account, it takes me to the student login page. In the future registering a teacher should take users to the teacher home page and students to their home page (once those pages are finished)

**Comment by rsgc-dunphy-j** [comment]
teacher register now redirects to teacher login

**Comment by rgordonathome** [comment]
This issue was created without necessary categorization (label, milestone, assignee).
