### ISSUE TITLE
Create a Page Wiki for Schmee (PS Mr. Ruscitti likes the name)

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RateMySchmeacher#2]
Can someone create a wiki with a list of user stories (features of the app). You can watch the video to see what Mr. Ruscitti's feedback was.
https://youtu.be/jSG0_ePWYNU

**Comment by rsgc-dunphy-j** [comment]
ill get a paper prototype going

**Comment by rsgc-edwards-g** [comment]
This doesn't need a paper prototype. You just need to edit the Wiki page in this project and then close this issue with a link to the Wiki (probably). If you need help formatting, look at the Wiki page I did for the door app.

**Comment by rsgc-dunphy-j** [comment]
Ill add to the page as features (shmeeatures) arise

**Comment by rgordonathome** [comment]
The [wiki](https://github.com/rsgc-edwards-g/RateMySchmeacher/wiki) for features for the application seems very sparse. See my comments on issue #1 , I heard a lot of feedback from Mr. Ruscitti. In the paper prototypes I see a lot of features not described in nearly enough detail (compare the list of features in this group's [wiki](https://github.com/rsgc-edwards-g/RateMySchmeacher/wiki) to the two exemplars given [here](https://github.com/rsgc-ics4u-2015/curriculum-organizer/wiki) and [here](https://github.com/rsgc-ics4u-2015/sbg/wiki) and even to the [Attendance wiki](https://github.com/rsgc-ics4u-2015/attendance/wiki). @rsgc-dunphy-j the wiki for RateMyScheacher needs a lot more detail.

**Comment by rsgc-dunphy-j** [comment]
with sufficient detail added, i believe the wiki page to be up to date.
