### ISSUE TITLE
Create Logout Button Link

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RateMySchmeacher#20]
I'm not sure whether we'll need two logout pages or just one.

**Comment by rsgc-dunphy-j** [comment]
We probably only need one logout page, if we even need a dedicated page for it

**Comment by rsgc-power-r** [comment]
We probably just need a button

**Comment by rsgc-edwards-g** [comment]
If you look at Mr. Gordon's example, he has an entire Logout page.

**Comment by rsgc-dunphy-j** [comment]
Phrasing issue here, its not a page, just a file that kills the session.
Ill get it working

**Comment by rgordonathome** [comment]
Suggest setting this issue with milestone sprint4, deadline February 11.

**Comment by rsgc-dunphy-j** [comment]
db29ed9a4b252e1cfa72e95a6b630c2ce20adbc1
