### ISSUE TITLE
Create a separate header (php file) to appear at the top of each page

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RateMySchmeacher#21]
I believe, if you write a php file with a header, we can use an 'include' statement to have it appear on each page.

**Comment by rsgc-power-r** [comment]
Started working on the header
https://github.com/rsgc-edwards-g/RateMySchmeacher/commit/778cb36dd74651a7fc2f30e6661c985c547c5054

**Comment by rsgc-edwards-g** [comment]
Insert this code at the top of a page to see if your header.php file works.
<?php include 'header.php'; ?>

**Comment by rsgc-power-r** [comment]
Rough work on the header was completed. Image and CSS needs to be updated in a later issue though.
https://github.com/rsgc-edwards-g/RateMySchmeacher/commit/e04b43438e3ab1ace2e199c328fa8944a039ce9e
