### ISSUE TITLE
Create a logo to be used in the Header

### ISSUE THREAD

**Issue by rsgc-power-r** [rsgc-edwards-g/RateMySchmeacher#25]
Design a thumbnail logo

**Comment by rsgc-power-r** [comment]
![logo draft1](https://cloud.githubusercontent.com/assets/14296590/13435629/323e7946-dfa9-11e5-89c9-870169de3193.jpg)
Please give some feedback, this is obviously a draft.

**Comment by rsgc-dunphy-j** [comment]
*Shmeedback

**Comment by rsgc-power-r** [comment]
fed4da84e59021dfa3755cff097bc52436a70fde
Uploaded the new file to the header
