### ISSUE TITLE
Move all code from <Head> to <Body>

### ISSUE THREAD

**Issue by rsgc-power-r** [rsgc-edwards-g/RateMySchmeacher#28]
Since the <header> CSS will be used for the Header.php file, all code should be removed from the <header>. Code can be placed after it.

**Comment by rsgc-edwards-g** [comment]
Do you still need to move any code @rsgc-power-r or is this done? There are still pages with code in the <head> section but your php include statement is in the <body> section.

**Comment by rsgc-power-r** [comment]
As long as it is just the include statement, it is complete
