### ISSUE TITLE
Determine what the Ratings will be based on

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RateMySchmeacher#3]
Mr. Ruscitti doesn't think we should have an overall rating. Based on John's rating page, we have Understanding, Entertaining and Productive

**Comment by rsgc-edwards-g** [comment]
I'm going to list all of the rating categories we have and add new ones as we think of them.
EXISTING:
- Understanding
- Entertaining
- Productive

**Comment by rsgc-edwards-g** [comment]
I think a pace of class rating might be useful. Any thoughts on that?

**Comment by rsgc-edwards-g** [comment]
I think class structure should also be rated. Maybe in an organization category. 

If we collect a number of possible rating categories, we can present them to Mr. Ruscitti and he can help us choose which ones we include.

**Comment by rsgc-edwards-g** [comment]
Do you think an "Engaging" category is useful or necessary or could we group it in with another category?

**Comment by rsgc-edwards-g** [comment]
The list up until now:
- Understanding
- Entertaining
- Engaging
- Productive
- Pace
- Organization
- Work-load???

Any thoughts?

**Comment by rsgc-power-r** [comment]
That seems like a good list of attributes to rate the class on, but do you think we could work it down to maybe... 5?

Keep in mind, Shmee should be minimalistic and quick so students review classes frequently.

**Comment by rsgc-edwards-g** [comment]
I completely agree but I thought we could keep this as a list of potential categories and then narrow it down together with Mr. Ruscitti.

**Comment by rgordonathome** [comment]
This issue did not have an assignee – gents, remember, this is a requirement.
