### ISSUE TITLE
Add some courses

### ISSUE THREAD

**Issue by rsgc-dunphy-j** [rsgc-edwards-g/RateMySchmeacher#30]
The rating page is functional, but in order for ratings to be meaningful, they need to be connected to a course and a class, so we need these things to exist

**Comment by rsgc-edwards-g** [comment]
I have a data dump from Ms. Fitz and I'll use it to get the courses and everything into the database.

**Comment by rsgc-edwards-g** [comment]
I am currently adding everything I can to the database. I'm making sure each of my text files work for inserting data so that we can insert everything in again if we have to reset our database.
