### ISSUE TITLE
Resolve Boolean column problem

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RateMySchmeacher#35]
I've tried to enter a Boolean value into a column in the students_has_courses table but I couldn't get the syntax correct. Is there any way for me to resolve this issue?

**Comment by rsgc-power-r** [comment]
what syntax did you try using?

**Comment by rsgc-edwards-g** [comment]
For now, all the student has courses items we have are all true, so we can ignore this in our logic. If we only allow teachers to add and drop students through the year, this field will be completely irrelevant as we can just add or delete items in the students_has_courses table
