### ISSUE TITLE
We need to get classes going

### ISSUE THREAD

**Issue by rsgc-dunphy-j** [rsgc-edwards-g/RateMySchmeacher#36]
In order to have the ratings be meaningful we need to have classes and some way to pair them with ratings

**Comment by rsgc-edwards-g** [comment]
Pairing should be easy but Ms. Wagar couldn't get a full list of classes with dates. For now, can we just enter some fake "classes" to get the rating to class connection logic going?

**Comment by rsgc-edwards-g** [comment]
Deleted classes in the database with d46ec50d1a5ad7fee38aaa0cf3e2e2ce3e97c1b2.
