### ISSUE TITLE
Change the student register page

### ISSUE THREAD

**Issue by rsgc-edwards-g** [rsgc-edwards-g/RateMySchmeacher#40]
There is data in the database for each student already so we don't need to have them create accounts with new names. We can simply have them enter their names and their desired usernames and passwords in order for them to set up their account.

**Comment by rsgc-dunphy-j** [comment]
We would need to add a field to the database for proposed username and password to be confirmed as the username and password with an email to the real account holder

**Comment by rsgc-edwards-g** [comment]
I agree with @rsgc-dunphy-j that we would need to be able to confirm a student's identity via email. However, I'm not sure if it's necessary to add a confirmation field to the database if we send the emails from the start rather than send confirmation emails. @rgordonatrsgc we would have to set the website up on another server either way due to our emailing of users, correct?
