### ISSUE TITLE
Get feedback on the Paper Prototype

### ISSUE THREAD

**Issue by rsgc-power-r** [rsgc-edwards-g/RateMySchmeacher#5]
John and Ryan are gonna get people to run through the paper prototype.

**Comment by rsgc-edwards-g** [comment]
https://youtu.be/jSG0_ePWYNU
First round of feedback from Ruscitti. (I posted this earlier)

**Comment by rsgc-dunphy-j** [comment]
frodi send the video!

**Comment by rsgc-power-r** [comment]
Here is a link to the video:
https://www.youtube.com/watch?v=e00JnjKekMQ

This feedback will assist in improving the interface of Shmee

**Comment by rgordonathome** [comment]
@rsgc-power-r the video you posted three days ago is a private link. Needs to be changed to unlisted before I can include it in considerations for marks.

Also, what was the result of the feedback? Where are your notes? What issues have been created out of the feedback session? It's not enough to simply links to the video – there needs to be some tracking of  what you took away from the feedback session.

**Comment by rsgc-power-r** [comment]
Fixed

**Comment by rgordonathome** [comment]
Hey @rsgc-power-r – per note from above –  what was the result of the feedback? Where are your notes? What issues have been created out of the feedback session? Please document clearly.

**Comment by rsgc-power-r** [comment]
Notes of changes based on this specific run through:
- Changed question on register page from "Teacher:" to "Are you a Teacher?"
- Small changes based on quality and continuity were made (same/missing classes)
- No Sign Out buttons
- No back buttons

Feedback:
- From what was seen, it "Felt unfinished" (Michael Wrana), but what we had was good.
- Missing buttons, which could be easily fixed
