### ISSUE TITLE
Create password verification field on activation page

### ISSUE THREAD

**Issue by rgordonathome** [rsgc-edwards-g/RateMySchmeacher#53]
Users are left open to make a typo when they provide their new password:

![screen shot 2016-04-17 at 4 25 25 pm](https://cloud.githubusercontent.com/assets/2380516/14589806/12037e1c-04b9-11e6-87b3-e9c4c66ad4d2.png)

Provide a "verify your password" field where the user has to enter the password again.

If the passwords do not match, allow them to make that correction.

This is a pretty standard practice when users are creating passwords on a website.

**Comment by rsgc-dunphy-j** [comment]
im pretty sure i did it but i cant see the register page so someone check and close the issue pretty please

**Comment by rsgc-dunphy-j** [comment]
ok is good
