### ISSUE TITLE
Authentication Research

### ISSUE THREAD

**Issue by rsgc-dunphy-j** [rsgc-edwards-g/RateMySchmeacher#8]
I will be researching Mr. Gordon's curriculum tracker's authentication form and attempt to replicate it in Shmee.

**Comment by rgordonathome** [comment]
@rsgc-dunphy-j there's no real need for 'research' here – work with @rsgc-edwards-g to ensure the database is running, and then modify the code that I posted to work with your group's application.

If you want a hand working through the exemplar, ask me in class or find me outside of class time. I'm happy to help.
